### ISSUE TITLE
Error: cannot parse quote (") in table name

### ISSUE THREAD

**Issue by derekdreery** [yosymfony/Toml#10]
Here's a simple failing example

```toml
[test."a.sring.with.dots"]
test_value = "string"
```
